import type { Country } from '@/types';

export const COUNTRIES: Country[] = [
  { id: 'th', isoCode: 'TH', nameJa: 'タイ', nameEn: 'Thailand', flag: '🇹🇭', region: 'アジア', continent: 'アジア', mapX: 67, mapY: 52, accent: '#2F6EB5' },
  { id: 'kr', isoCode: 'KR', nameJa: '韓国', nameEn: 'South Korea', flag: '🇰🇷', region: 'アジア', continent: 'アジア', mapX: 75, mapY: 36, accent: '#315B9B' },
  { id: 'sg', isoCode: 'SG', nameJa: 'シンガポール', nameEn: 'Singapore', flag: '🇸🇬', region: 'アジア', continent: 'アジア', mapX: 68, mapY: 62, accent: '#D9363E' },
  { id: 'vn', isoCode: 'VN', nameJa: 'ベトナム', nameEn: 'Vietnam', flag: '🇻🇳', region: 'アジア', continent: 'アジア', mapX: 70, mapY: 53, accent: '#D62828' },
  { id: 'id', isoCode: 'ID', nameJa: 'インドネシア', nameEn: 'Indonesia', flag: '🇮🇩', region: 'アジア', continent: 'アジア', mapX: 72, mapY: 68, accent: '#C83D3D' },
  { id: 'cn', isoCode: 'CN', nameJa: '中国', nameEn: 'China', flag: '🇨🇳', region: 'アジア', continent: 'アジア', mapX: 68, mapY: 35, accent: '#D62C2C' },
  { id: 'tw', isoCode: 'TW', nameJa: '台湾', nameEn: 'Taiwan', flag: '🇹🇼', region: 'アジア', continent: 'アジア', mapX: 75, mapY: 45, accent: '#365BB7' },
  { id: 'in', isoCode: 'IN', nameJa: 'インド', nameEn: 'India', flag: '🇮🇳', region: 'アジア', continent: 'アジア', mapX: 57, mapY: 49, accent: '#EF8B2C' },
  { id: 'my', isoCode: 'MY', nameJa: 'マレーシア', nameEn: 'Malaysia', flag: '🇲🇾', region: 'アジア', continent: 'アジア', mapX: 67, mapY: 61, accent: '#244F9E' },
  { id: 'ph', isoCode: 'PH', nameJa: 'フィリピン', nameEn: 'Philippines', flag: '🇵🇭', region: 'アジア', continent: 'アジア', mapX: 77, mapY: 55, accent: '#3158A8' },
  { id: 'tr', isoCode: 'TR', nameJa: 'トルコ', nameEn: 'Turkey', flag: '🇹🇷', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 50, mapY: 35, accent: '#D73838' },
  { id: 'it', isoCode: 'IT', nameJa: 'イタリア', nameEn: 'Italy', flag: '🇮🇹', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 45, mapY: 36, accent: '#2D9B63' },
  { id: 'fr', isoCode: 'FR', nameJa: 'フランス', nameEn: 'France', flag: '🇫🇷', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 41, mapY: 34, accent: '#315AAB' },
  { id: 'es', isoCode: 'ES', nameJa: 'スペイン', nameEn: 'Spain', flag: '🇪🇸', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 39, mapY: 39, accent: '#D8A22A' },
  { id: 'de', isoCode: 'DE', nameJa: 'ドイツ', nameEn: 'Germany', flag: '🇩🇪', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 43, mapY: 31, accent: '#36312C' },
  { id: 'gb', isoCode: 'GB', nameJa: 'イギリス', nameEn: 'United Kingdom', flag: '🇬🇧', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 39, mapY: 29, accent: '#325AA8' },
  { id: 'is', isoCode: 'IS', nameJa: 'アイスランド', nameEn: 'Iceland', flag: '🇮🇸', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 35, mapY: 21, accent: '#3167A8' },
  { id: 'pt', isoCode: 'PT', nameJa: 'ポルトガル', nameEn: 'Portugal', flag: '🇵🇹', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 37, mapY: 39, accent: '#2A9566' },
  { id: 'nl', isoCode: 'NL', nameJa: 'オランダ', nameEn: 'Netherlands', flag: '🇳🇱', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 42, mapY: 30, accent: '#D76738' },
  { id: 'gr', isoCode: 'GR', nameJa: 'ギリシャ', nameEn: 'Greece', flag: '🇬🇷', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 47, mapY: 40, accent: '#2C84C8' },
  { id: 'fi', isoCode: 'FI', nameJa: 'フィンランド', nameEn: 'Finland', flag: '🇫🇮', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 47, mapY: 23, accent: '#3B6FA7' },
  { id: 'us', isoCode: 'US', nameJa: 'アメリカ', nameEn: 'United States', flag: '🇺🇸', region: '北米', continent: '北米', mapX: 20, mapY: 37, accent: '#3159A4' },
  { id: 'ca', isoCode: 'CA', nameJa: 'カナダ', nameEn: 'Canada', flag: '🇨🇦', region: '北米', continent: '北米', mapX: 18, mapY: 25, accent: '#D54242' },
  { id: 'mx', isoCode: 'MX', nameJa: 'メキシコ', nameEn: 'Mexico', flag: '🇲🇽', region: '北米', continent: '北米', mapX: 20, mapY: 49, accent: '#279B64' },
  { id: 'cu', isoCode: 'CU', nameJa: 'キューバ', nameEn: 'Cuba', flag: '🇨🇺', region: '北米', continent: '北米', mapX: 27, mapY: 51, accent: '#3267A8' },
  { id: 'pe', isoCode: 'PE', nameJa: 'ペルー', nameEn: 'Peru', flag: '🇵🇪', region: '南米', continent: '南米', mapX: 31, mapY: 70, accent: '#C83D3D' },
  { id: 'br', isoCode: 'BR', nameJa: 'ブラジル', nameEn: 'Brazil', flag: '🇧🇷', region: '南米', continent: '南米', mapX: 36, mapY: 70, accent: '#36A666' },
  { id: 'ar', isoCode: 'AR', nameJa: 'アルゼンチン', nameEn: 'Argentina', flag: '🇦🇷', region: '南米', continent: '南米', mapX: 33, mapY: 83, accent: '#5CA7D8' },
  { id: 'cl', isoCode: 'CL', nameJa: 'チリ', nameEn: 'Chile', flag: '🇨🇱', region: '南米', continent: '南米', mapX: 30, mapY: 82, accent: '#D74747' },
  { id: 'co', isoCode: 'CO', nameJa: 'コロンビア', nameEn: 'Colombia', flag: '🇨🇴', region: '南米', continent: '南米', mapX: 31, mapY: 61, accent: '#DAB334' },
  { id: 'ma', isoCode: 'MA', nameJa: 'モロッコ', nameEn: 'Morocco', flag: '🇲🇦', region: 'アフリカ', continent: 'アフリカ', mapX: 43, mapY: 48, accent: '#C73737' },
  { id: 'eg', isoCode: 'EG', nameJa: 'エジプト', nameEn: 'Egypt', flag: '🇪🇬', region: 'アフリカ', continent: 'アフリカ', mapX: 51, mapY: 48, accent: '#C84141' },
  { id: 'za', isoCode: 'ZA', nameJa: '南アフリカ', nameEn: 'South Africa', flag: '🇿🇦', region: 'アフリカ', continent: 'アフリカ', mapX: 52, mapY: 82, accent: '#2D9B63' },
  { id: 'ke', isoCode: 'KE', nameJa: 'ケニア', nameEn: 'Kenya', flag: '🇰🇪', region: 'アフリカ', continent: 'アフリカ', mapX: 56, mapY: 64, accent: '#2F8B57' },
  { id: 'au', isoCode: 'AU', nameJa: 'オーストラリア', nameEn: 'Australia', flag: '🇦🇺', region: 'オセアニア', continent: 'オセアニア', mapX: 79, mapY: 78, accent: '#315DAB' },
  { id: 'nz', isoCode: 'NZ', nameJa: 'ニュージーランド', nameEn: 'New Zealand', flag: '🇳🇿', region: 'オセアニア', continent: 'オセアニア', mapX: 87, mapY: 86, accent: '#315DAB' },
  { id: 'fj', isoCode: 'FJ', nameJa: 'フィジー', nameEn: 'Fiji', flag: '🇫🇯', region: 'オセアニア', continent: 'オセアニア', mapX: 91, mapY: 75, accent: '#62ADD7' },
  { id: 'mn', isoCode: 'MN', nameJa: 'モンゴル', nameEn: 'Mongolia', flag: '🇲🇳', region: 'アジア', continent: 'アジア', mapX: 78.96, mapY: 22, accent: '#248969' },
  { id: 'kp', isoCode: 'KP', nameJa: '北朝鮮', nameEn: 'North Korea', flag: '🇰🇵', region: 'アジア', continent: 'アジア', mapX: 85.45, mapY: 26.06, accent: '#268287' },
  { id: 'bn', isoCode: 'BN', nameJa: 'ブルネイ', nameEn: 'Brunei', flag: '🇧🇳', region: 'アジア', continent: 'アジア', mapX: 81.93, mapY: 47.19, accent: '#2E737F' },
  { id: 'kh', isoCode: 'KH', nameJa: 'カンボジア', nameEn: 'Cambodia', flag: '🇰🇭', region: 'アジア', continent: 'アジア', mapX: 79.14, mapY: 42.49, accent: '#27867E' },
  { id: 'la', isoCode: 'LA', nameJa: 'ラオス', nameEn: 'Laos', flag: '🇱🇦', region: 'アジア', continent: 'アジア', mapX: 78.82, mapY: 39.14, accent: '#268764' },
  { id: 'mm', isoCode: 'MM', nameJa: 'ミャンマー', nameEn: 'Myanmar', flag: '🇲🇲', region: 'アジア', continent: 'アジア', mapX: 76.94, mapY: 38.3, accent: '#248967' },
  { id: 'tl', isoCode: 'TL', nameJa: '東ティモール', nameEn: 'Timor-Leste', flag: '🇹🇱', region: 'アジア', continent: 'アジア', mapX: 85, mapY: 55.24, accent: '#1F8E7E' },
  { id: 'af', isoCode: 'AF', nameJa: 'アフガニスタン', nameEn: 'Afghanistan', flag: '🇦🇫', region: 'アジア', continent: 'アジア', mapX: 68.83, mapY: 29.48, accent: '#2F707F' },
  { id: 'bd', isoCode: 'BD', nameJa: 'バングラデシュ', nameEn: 'Bangladesh', flag: '🇧🇩', region: 'アジア', continent: 'アジア', mapX: 75.15, mapY: 36.03, accent: '#2E7F7E' },
  { id: 'bt', isoCode: 'BT', nameJa: 'ブータン', nameEn: 'Bhutan', flag: '🇧🇹', region: 'アジア', continent: 'アジア', mapX: 75.15, mapY: 33.65, accent: '#2E6B7F' },
  { id: 'mv', isoCode: 'MV', nameJa: 'モルディブ', nameEn: 'Maldives', flag: '🇲🇻', region: 'アジア', continent: 'アジア', mapX: 72, mapY: 46, accent: '#248977' },
  { id: 'np', isoCode: 'NP', nameJa: 'ネパール', nameEn: 'Nepal', flag: '🇳🇵', region: 'アジア', continent: 'アジア', mapX: 73.44, mapY: 33.16, accent: '#24728A' },
  { id: 'pk', isoCode: 'PK', nameJa: 'パキスタン', nameEn: 'Pakistan', flag: '🇵🇰', region: 'アジア', continent: 'アジア', mapX: 69.28, mapY: 31.76, accent: '#238B78' },
  { id: 'lk', isoCode: 'LK', nameJa: 'スリランカ', nameEn: 'Sri Lanka', flag: '🇱🇰', region: 'アジア', continent: 'アジア', mapX: 72.45, mapY: 45.39, accent: '#268774' },
  { id: 'kz', isoCode: 'KZ', nameJa: 'カザフスタン', nameEn: 'Kazakhstan', flag: '🇰🇿', region: 'アジア', continent: 'アジア', mapX: 68.31, mapY: 21.69, accent: '#267287' },
  { id: 'kg', isoCode: 'KG', nameJa: 'キルギス', nameEn: 'Kyrgyzstan', flag: '🇰🇬', region: 'アジア', continent: 'アジア', mapX: 70.65, mapY: 25.4, accent: '#27867D' },
  { id: 'tj', isoCode: 'TJ', nameJa: 'タジキスタン', nameEn: 'Tajikistan', flag: '🇹🇯', region: 'アジア', continent: 'アジア', mapX: 69.71, mapY: 26.99, accent: '#1F8E7A' },
  { id: 'tm', isoCode: 'TM', nameJa: 'トルクメニスタン', nameEn: 'Turkmenistan', flag: '🇹🇲', region: 'アジア', continent: 'アジア', mapX: 66.35, mapY: 26.66, accent: '#1F8E7F' },
  { id: 'uz', isoCode: 'UZ', nameJa: 'ウズベキスタン', nameEn: 'Uzbekistan', flag: '🇺🇿', region: 'アジア', continent: 'アジア', mapX: 68.05, mapY: 25.46, accent: '#307E77' },
  { id: 'am', isoCode: 'AM', nameJa: 'アルメニア', nameEn: 'Armenia', flag: '🇦🇲', region: 'アジア', continent: 'アジア', mapX: 62.56, mapY: 26.21, accent: '#2F7F60' },
  { id: 'az', isoCode: 'AZ', nameJa: 'アゼルバイジャン', nameEn: 'Azerbaijan', flag: '🇦🇿', region: 'アジア', continent: 'アジア', mapX: 63.12, mapY: 26.13, accent: '#2F7F71' },
  { id: 'bh', isoCode: 'BH', nameJa: 'バーレーン', nameEn: 'Bahrain', flag: '🇧🇭', region: 'アジア', continent: 'アジア', mapX: 64, mapY: 36, accent: '#2E7B7F' },
  { id: 'cy', isoCode: 'CY', nameJa: 'キプロス', nameEn: 'Cyprus', flag: '🇨🇾', region: 'アジア', continent: 'アジア', mapX: 59.23, mapY: 29.19, accent: '#2D7280' },
  { id: 'ge', isoCode: 'GE', nameJa: 'ジョージア', nameEn: 'Georgia', flag: '🇬🇪', region: 'アジア', continent: 'アジア', mapX: 62.04, mapY: 24.84, accent: '#2A8376' },
  { id: 'iq', isoCode: 'IQ', nameJa: 'イラク', nameEn: 'Iraq', flag: '🇮🇶', region: 'アジア', continent: 'アジア', mapX: 62.25, mapY: 30.14, accent: '#28866B' },
  { id: 'ir', isoCode: 'IR', nameJa: 'イラン', nameEn: 'Iran', flag: '🇮🇷', region: 'アジア', continent: 'アジア', mapX: 64.84, mapY: 30.37, accent: '#28866D' },
  { id: 'il', isoCode: 'IL', nameJa: 'イスラエル', nameEn: 'Israel', flag: '🇮🇱', region: 'アジア', continent: 'アジア', mapX: 59.75, mapY: 31.1, accent: '#288663' },
  { id: 'jo', isoCode: 'JO', nameJa: 'ヨルダン', nameEn: 'Jordan', flag: '🇯🇴', region: 'アジア', continent: 'アジア', mapX: 60.22, mapY: 31.43, accent: '#277386' },
  { id: 'kw', isoCode: 'KW', nameJa: 'クウェート', nameEn: 'Kuwait', flag: '🇰🇼', region: 'アジア', continent: 'アジア', mapX: 63.24, mapY: 32.56, accent: '#267787' },
  { id: 'lb', isoCode: 'LB', nameJa: 'レバノン', nameEn: 'Lebanon', flag: '🇱🇧', region: 'アジア', continent: 'アジア', mapX: 59.96, mapY: 29.87, accent: '#268765' },
  { id: 'om', isoCode: 'OM', nameJa: 'オマーン', nameEn: 'Oman', flag: '🇴🇲', region: 'アジア', continent: 'アジア', mapX: 65.63, mapY: 37.19, accent: '#24888A' },
  { id: 'qa', isoCode: 'QA', nameJa: 'カタール', nameEn: 'Qatar', flag: '🇶🇦', region: 'アジア', continent: 'アジア', mapX: 64.21, mapY: 34.95, accent: '#227A8C' },
  { id: 'sa', isoCode: 'SA', nameJa: 'サウジアラビア', nameEn: 'Saudi Arabia', flag: '🇸🇦', region: 'アジア', continent: 'アジア', mapX: 62.28, mapY: 35.63, accent: '#208D7B' },
  { id: 'sy', isoCode: 'SY', nameJa: 'シリア', nameEn: 'Syria', flag: '🇸🇾', region: 'アジア', continent: 'アジア', mapX: 60.66, mapY: 29.16, accent: '#1F748E' },
  { id: 'ae', isoCode: 'AE', nameJa: 'アラブ首長国連邦', nameEn: 'United Arab Emirates', flag: '🇦🇪', region: 'アジア', continent: 'アジア', mapX: 65.04, mapY: 35.58, accent: '#2F717F' },
  { id: 'ye', isoCode: 'YE', nameJa: 'イエメン', nameEn: 'Yemen', flag: '🇾🇪', region: 'アジア', continent: 'アジア', mapX: 63.06, mapY: 40.7, accent: '#2D6A80' },
  { id: 'al', isoCode: 'AL', nameJa: 'アルバニア', nameEn: 'Albania', flag: '🇦🇱', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 55.59, mapY: 25.46, accent: '#329F9D' },
  { id: 'ad', isoCode: 'AD', nameJa: 'アンドラ', nameEn: 'Andorra', flag: '🇦🇩', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 46, mapY: 26, accent: '#32659F' },
  { id: 'at', isoCode: 'AT', nameJa: 'オーストリア', nameEn: 'Austria', flag: '🇦🇹', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 53.72, mapY: 21.62, accent: '#32929F' },
  { id: 'by', isoCode: 'BY', nameJa: 'ベラルーシ', nameEn: 'Belarus', flag: '🇧🇾', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 57.82, mapY: 18.15, accent: '#319CA0' },
  { id: 'be', isoCode: 'BE', nameJa: 'ベルギー', nameEn: 'Belgium', flag: '🇧🇪', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 51.22, mapY: 19.86, accent: '#3175A0' },
  { id: 'ba', isoCode: 'BA', nameJa: 'ボスニア・ヘルツェゴビナ', nameEn: 'Bosnia and Herzegovina', flag: '🇧🇦', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 54.96, mapY: 23.75, accent: '#327C9F' },
  { id: 'bg', isoCode: 'BG', nameJa: 'ブルガリア', nameEn: 'Bulgaria', flag: '🇧🇬', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 56.95, mapY: 24.51, accent: '#3172A0' },
  { id: 'hr', isoCode: 'HR', nameJa: 'クロアチア', nameEn: 'Croatia', flag: '🇭🇷', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 54.58, mapY: 23.39, accent: '#2B83A6' },
  { id: 'cz', isoCode: 'CZ', nameJa: 'チェコ', nameEn: 'Czech Republic', flag: '🇨🇿', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 54.37, mapY: 20.37, accent: '#3061A1' },
  { id: 'dk', isoCode: 'DK', nameJa: 'デンマーク', nameEn: 'Denmark', flag: '🇩🇰', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 52.85, mapY: 16.57, accent: '#2F91A2' },
  { id: 'ee', isoCode: 'EE', nameJa: 'エストニア', nameEn: 'Estonia', flag: '🇪🇪', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 57.21, mapY: 15.1, accent: '#2E61A3' },
  { id: 'hu', isoCode: 'HU', nameJa: 'ハンガリー', nameEn: 'Hungary', flag: '🇭🇺', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 55.37, mapY: 21.83, accent: '#2B7DA6' },
  { id: 'ie', isoCode: 'IE', nameJa: 'アイルランド', nameEn: 'Ireland', flag: '🇮🇪', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 47.82, mapY: 18.17, accent: '#2B5EA6' },
  { id: 'lv', isoCode: 'LV', nameJa: 'ラトビア', nameEn: 'Latvia', flag: '🇱🇻', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 56.9, mapY: 16.18, accent: '#277AAA' },
  { id: 'li', isoCode: 'LI', nameJa: 'リヒテンシュタイン', nameEn: 'Liechtenstein', flag: '🇱🇮', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 51, mapY: 23, accent: '#2896A9' },
  { id: 'lt', isoCode: 'LT', nameJa: 'リトアニア', nameEn: 'Lithuania', flag: '🇱🇹', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 56.65, mapY: 17.17, accent: '#277FAA' },
  { id: 'lu', isoCode: 'LU', nameJa: 'ルクセンブルク', nameEn: 'Luxembourg', flag: '🇱🇺', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 51.66, mapY: 20.35, accent: '#277CAA' },
  { id: 'mt', isoCode: 'MT', nameJa: 'マルタ', nameEn: 'Malta', flag: '🇲🇹', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 53, mapY: 28, accent: '#2695AB' },
  { id: 'md', isoCode: 'MD', nameJa: 'モルドバ', nameEn: 'Moldova', flag: '🇲🇩', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 57.89, mapY: 22.02, accent: '#275EAA' },
  { id: 'mc', isoCode: 'MC', nameJa: 'モナコ', nameEn: 'Monaco', flag: '🇲🇨', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 49, mapY: 26, accent: '#2760AA' },
  { id: 'me', isoCode: 'ME', nameJa: 'モンテネグロ', nameEn: 'Montenegro', flag: '🇲🇪', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 55.4, mapY: 24.56, accent: '#275BAA' },
  { id: 'mk', isoCode: 'MK', nameJa: '北マケドニア', nameEn: 'North Macedonia', flag: '🇲🇰', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 56.02, mapY: 25.22, accent: '#27A8AA' },
  { id: 'no', isoCode: 'NO', nameJa: 'ノルウェー', nameEn: 'Norway', flag: '🇳🇴', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 55.12, mapY: 7.85, accent: '#255BAD' },
  { id: 'pl', isoCode: 'PL', nameJa: 'ポーランド', nameEn: 'Poland', flag: '🇵🇱', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 55.36, mapY: 19.16, accent: '#2490AE' },
  { id: 'ro', isoCode: 'RO', nameJa: 'ルーマニア', nameEn: 'Romania', flag: '🇷🇴', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 56.96, mapY: 22.68, accent: '#2158B0' },
  { id: 'ru', isoCode: 'RU', nameJa: 'ロシア', nameEn: 'Russia', flag: '🇷🇺', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 62.82, mapY: 13.58, accent: '#20ACB1' },
  { id: 'sm', isoCode: 'SM', nameJa: 'サンマリノ', nameEn: 'San Marino', flag: '🇸🇲', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 52, mapY: 25, accent: '#2075B1' },
  { id: 'rs', isoCode: 'RS', nameJa: 'セルビア', nameEn: 'Serbia', flag: '🇷🇸', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 55.8, mapY: 23.8, accent: '#20B1B1' },
  { id: 'sk', isoCode: 'SK', nameJa: 'スロバキア', nameEn: 'Slovakia', flag: '🇸🇰', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 55.42, mapY: 21, accent: '#2079B1' },
  { id: 'si', isoCode: 'SI', nameJa: 'スロベニア', nameEn: 'Slovenia', flag: '🇸🇮', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 54.18, mapY: 22.55, accent: '#207EB1' },
  { id: 'se', isoCode: 'SE', nameJa: 'スウェーデン', nameEn: 'Sweden', flag: '🇸🇪', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 54.7, mapY: 12.78, accent: '#2088B1' },
  { id: 'ch', isoCode: 'CH', nameJa: 'スイス', nameEn: 'Switzerland', flag: '🇨🇭', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 52.3, mapY: 22.14, accent: '#3083A1' },
  { id: 'ua', isoCode: 'UA', nameJa: 'ウクライナ', nameEn: 'Ukraine', flag: '🇺🇦', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 58.53, mapY: 20.99, accent: '#34629D' },
  { id: 'va', isoCode: 'VA', nameJa: 'バチカン市国', nameEn: 'Vatican City', flag: '🇻🇦', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 53, mapY: 26, accent: '#33739E' },
  { id: 'xk', isoCode: 'XK', nameJa: 'コソボ', nameEn: 'Kosovo', flag: '🇽🇰', region: 'ヨーロッパ', continent: 'ヨーロッパ', mapX: 55.82, mapY: 24.67, accent: '#3186A0' },
  { id: 'bz', isoCode: 'BZ', nameJa: 'ベリーズ', nameEn: 'Belize', flag: '🇧🇿', region: '北米', continent: '北米', mapX: 25.38, mapY: 39.69, accent: '#6F5A96' },
  { id: 'cr', isoCode: 'CR', nameJa: 'コスタリカ', nameEn: 'Costa Rica', flag: '🇨🇷', region: '北米', continent: '北米', mapX: 26.62, mapY: 44.18, accent: '#865A96' },
  { id: 'sv', isoCode: 'SV', nameJa: 'エルサルバドル', nameEn: 'El Salvador', flag: '🇸🇻', region: '北米', continent: '北米', mapX: 25.3, mapY: 41.77, accent: '#994AA5' },
  { id: 'gt', isoCode: 'GT', nameJa: 'グアテマラ', nameEn: 'Guatemala', flag: '🇬🇹', region: '北米', continent: '北米', mapX: 24.93, mapY: 40.7, accent: '#8A5997' },
  { id: 'hn', isoCode: 'HN', nameJa: 'ホンジュラス', nameEn: 'Honduras', flag: '🇭🇳', region: '北米', continent: '北米', mapX: 26.03, mapY: 41.28, accent: '#795798' },
  { id: 'ni', isoCode: 'NI', nameJa: 'ニカラグア', nameEn: 'Nicaragua', flag: '🇳🇮', region: '北米', continent: '北米', mapX: 26.35, mapY: 42.27, accent: '#8F519E' },
  { id: 'pa', isoCode: 'PA', nameJa: 'パナマ', nameEn: 'Panama', flag: '🇵🇦', region: '北米', continent: '北米', mapX: 27.71, mapY: 44.97, accent: '#6A4FA1' },
  { id: 'ag', isoCode: 'AG', nameJa: 'アンティグア・バーブーダ', nameEn: 'Antigua and Barbuda', flag: '🇦🇬', region: '北米', continent: '北米', mapX: 32, mapY: 51, accent: '#8F5A96' },
  { id: 'bs', isoCode: 'BS', nameJa: 'バハマ', nameEn: 'Bahamas', flag: '🇧🇸', region: '北米', continent: '北米', mapX: 28.34, mapY: 34.73, accent: '#915A96' },
  { id: 'bb', isoCode: 'BB', nameJa: 'バルバドス', nameEn: 'Barbados', flag: '🇧🇧', region: '北米', continent: '北米', mapX: 33, mapY: 53, accent: '#805A96' },
  { id: 'dm', isoCode: 'DM', nameJa: 'ドミニカ国', nameEn: 'Dominica', flag: '🇩🇲', region: '北米', continent: '北米', mapX: 32, mapY: 52, accent: '#775A96' },
  { id: 'do', isoCode: 'DO', nameJa: 'ドミニカ共和国', nameEn: 'Dominican Republic', flag: '🇩🇴', region: '北米', continent: '北米', mapX: 30.46, mapY: 38.86, accent: '#795A96' },
  { id: 'gd', isoCode: 'GD', nameJa: 'グレナダ', nameEn: 'Grenada', flag: '🇬🇩', region: '北米', continent: '北米', mapX: 32, mapY: 53, accent: '#795A96' },
  { id: 'ht', isoCode: 'HT', nameJa: 'ハイチ', nameEn: 'Haiti', flag: '🇭🇹', region: '北米', continent: '北米', mapX: 29.77, mapY: 38.75, accent: '#7F5798' },
  { id: 'jm', isoCode: 'JM', nameJa: 'ジャマイカ', nameEn: 'Jamaica', flag: '🇯🇲', region: '北米', continent: '北米', mapX: 28.52, mapY: 39.19, accent: '#90559B' },
  { id: 'kn', isoCode: 'KN', nameJa: 'セントクリストファー・ネービス', nameEn: 'Saint Kitts and Nevis', flag: '🇰🇳', region: '北米', continent: '北米', mapX: 31, mapY: 51, accent: '#86549C' },
  { id: 'lc', isoCode: 'LC', nameJa: 'セントルシア', nameEn: 'Saint Lucia', flag: '🇱🇨', region: '北米', continent: '北米', mapX: 32, mapY: 52, accent: '#6D549C' },
  { id: 'vc', isoCode: 'VC', nameJa: 'セントビンセント及びグレナディーン諸島', nameEn: 'Saint Vincent and the Grenadines', flag: '🇻🇨', region: '北米', continent: '北米', mapX: 32, mapY: 53, accent: '#865A96' },
  { id: 'tt', isoCode: 'TT', nameJa: 'トリニダード・トバゴ', nameEn: 'Trinidad and Tobago', flag: '🇹🇹', region: '北米', continent: '北米', mapX: 32.93, mapY: 43.77, accent: '#825A96' },
  { id: 'bo', isoCode: 'BO', nameJa: 'ボリビア', nameEn: 'Bolivia', flag: '🇧🇴', region: '南米', continent: '南米', mapX: 32.25, mapY: 59.72, accent: '#BBAF2A' },
  { id: 'ec', isoCode: 'EC', nameJa: 'エクアドル', nameEn: 'Ecuador', flag: '🇪🇨', region: '南米', continent: '南米', mapX: 28.2, mapY: 51.01, accent: '#BDAE28' },
  { id: 'gy', isoCode: 'GY', nameJa: 'ガイアナ', nameEn: 'Guyana', flag: '🇬🇾', region: '南米', continent: '南米', mapX: 33.63, mapY: 47.25, accent: '#C1B625' },
  { id: 'py', isoCode: 'PY', nameJa: 'パラグアイ', nameEn: 'Paraguay', flag: '🇵🇾', region: '南米', continent: '南米', mapX: 33.91, mapY: 63.91, accent: '#CBA81A' },
  { id: 'sr', isoCode: 'SR', nameJa: 'スリナム', nameEn: 'Suriname', flag: '🇸🇷', region: '南米', continent: '南米', mapX: 34.47, mapY: 47.75, accent: '#CDB518' },
  { id: 'uy', isoCode: 'UY', nameJa: 'ウルグアイ', nameEn: 'Uruguay', flag: '🇺🇾', region: '南米', continent: '南米', mapX: 34.44, mapY: 69.43, accent: '#B9882D' },
  { id: 've', isoCode: 'VE', nameJa: 'ベネズエラ', nameEn: 'Venezuela', flag: '🇻🇪', region: '南米', continent: '南米', mapX: 31.46, mapY: 45.89, accent: '#B9A12D' },
  { id: 'dz', isoCode: 'DZ', nameJa: 'アルジェリア', nameEn: 'Algeria', flag: '🇩🇿', region: 'アフリカ', continent: 'アフリカ', mapX: 50.69, mapY: 32.72, accent: '#748131' },
  { id: 'ao', isoCode: 'AO', nameJa: 'アンゴラ', nameEn: 'Angola', flag: '🇦🇴', region: 'アフリカ', continent: 'アフリカ', mapX: 54.78, mapY: 56.31, accent: '#7F7034' },
  { id: 'bj', isoCode: 'BJ', nameJa: 'ベナン', nameEn: 'Benin', flag: '🇧🇯', region: 'アフリカ', continent: 'アフリカ', mapX: 50.64, mapY: 44.31, accent: '#6E8033' },
  { id: 'bw', isoCode: 'BW', nameJa: 'ボツワナ', nameEn: 'Botswana', flag: '🇧🇼', region: 'アフリカ', continent: 'アフリカ', mapX: 56.82, mapY: 63.32, accent: '#806E33' },
  { id: 'bf', isoCode: 'BF', nameJa: 'ブルキナファソ', nameEn: 'Burkina Faso', flag: '🇧🇫', region: 'アフリカ', continent: 'アフリカ', mapX: 49.5, mapY: 42.73, accent: '#738033' },
  { id: 'bi', isoCode: 'BI', nameJa: 'ブルンジ', nameEn: 'Burundi', flag: '🇧🇮', region: 'アフリカ', continent: 'アフリカ', mapX: 58.33, mapY: 51.97, accent: '#6F8033' },
  { id: 'cv', isoCode: 'CV', nameJa: 'カーボベルデ', nameEn: 'Cabo Verde', flag: '🇨🇻', region: 'アフリカ', continent: 'アフリカ', mapX: 38, mapY: 50, accent: '#6C8132' },
  { id: 'cm', isoCode: 'CM', nameJa: 'カメルーン', nameEn: 'Cameroon', flag: '🇨🇲', region: 'アフリカ', continent: 'アフリカ', mapX: 53.56, mapY: 45.8, accent: '#778132' },
  { id: 'cf', isoCode: 'CF', nameJa: '中央アフリカ', nameEn: 'Central African Republic', flag: '🇨🇫', region: 'アフリカ', continent: 'アフリカ', mapX: 55.78, mapY: 46.16, accent: '#818132' },
  { id: 'td', isoCode: 'TD', nameJa: 'チャド', nameEn: 'Chad', flag: '🇹🇩', region: 'アフリカ', continent: 'アフリカ', mapX: 55.08, mapY: 41.69, accent: '#8F8124' },
  { id: 'km', isoCode: 'KM', nameJa: 'コモロ', nameEn: 'Comoros', flag: '🇰🇲', region: 'アフリカ', continent: 'アフリカ', mapX: 59, mapY: 67, accent: '#7A882B' },
  { id: 'cg', isoCode: 'CG', nameJa: 'コンゴ共和国', nameEn: 'Republic of the Congo', flag: '🇨🇬', region: 'アフリカ', continent: 'アフリカ', mapX: 54.13, mapY: 50.48, accent: '#7F8132' },
  { id: 'cd', isoCode: 'CD', nameJa: 'コンゴ民主共和国', nameEn: 'Democratic Republic of the Congo', flag: '🇨🇩', region: 'アフリカ', continent: 'アフリカ', mapX: 56.27, mapY: 52.31, accent: '#817E32' },
  { id: 'ci', isoCode: 'CI', nameJa: 'コートジボワール', nameEn: 'Côte d\'Ivoire', flag: '🇨🇮', region: 'アフリカ', continent: 'アフリカ', mapX: 48.32, mapY: 45.4, accent: '#7D8132' },
  { id: 'dj', isoCode: 'DJ', nameJa: 'ジブチ', nameEn: 'Djibouti', flag: '🇩🇯', region: 'アフリカ', continent: 'アフリカ', mapX: 61.81, mapY: 42.97, accent: '#817931' },
  { id: 'gq', isoCode: 'GQ', nameJa: '赤道ギニア', nameEn: 'Equatorial Guinea', flag: '🇬🇶', region: 'アフリカ', continent: 'アフリカ', mapX: 52.82, mapY: 49.03, accent: '#73842E' },
  { id: 'er', isoCode: 'ER', nameJa: 'エリトリア', nameEn: 'Eritrea', flag: '🇪🇷', region: 'アフリカ', continent: 'アフリカ', mapX: 61.01, mapY: 41.12, accent: '#827730' },
  { id: 'sz', isoCode: 'SZ', nameJa: 'エスワティニ', nameEn: 'Eswatini', flag: '🇸🇿', region: 'アフリカ', continent: 'アフリカ', mapX: 58.73, mapY: 65.74, accent: '#648F24' },
  { id: 'et', isoCode: 'ET', nameJa: 'エチオピア', nameEn: 'Ethiopia', flag: '🇪🇹', region: 'アフリカ', continent: 'アフリカ', mapX: 61.03, mapY: 44.61, accent: '#827A30' },
  { id: 'ga', isoCode: 'GA', nameJa: 'ガボン', nameEn: 'Gabon', flag: '🇬🇦', region: 'アフリカ', continent: 'アフリカ', mapX: 53.27, mapY: 50.32, accent: '#837E2F' },
  { id: 'gm', isoCode: 'GM', nameJa: 'ガンビア', nameEn: 'Gambia', flag: '🇬🇲', region: 'アフリカ', continent: 'アフリカ', mapX: 45.75, mapY: 41.95, accent: '#79842E' },
  { id: 'gh', isoCode: 'GH', nameJa: 'ガーナ', nameEn: 'Ghana', flag: '🇬🇭', region: 'アフリカ', continent: 'アフリカ', mapX: 49.72, mapY: 45.15, accent: '#80842E' },
  { id: 'gn', isoCode: 'GN', nameJa: 'ギニア', nameEn: 'Guinea', flag: '🇬🇳', region: 'アフリカ', continent: 'アフリカ', mapX: 46.9, mapY: 43.92, accent: '#77842E' },
  { id: 'gw', isoCode: 'GW', nameJa: 'ギニアビサウ', nameEn: 'Guinea-Bissau', flag: '🇬🇼', region: 'アフリカ', continent: 'アフリカ', mapX: 45.78, mapY: 42.9, accent: '#6A842E' },
  { id: 'ls', isoCode: 'LS', nameJa: 'レソト', nameEn: 'Lesotho', flag: '🇱🇸', region: 'アフリカ', continent: 'アフリカ', mapX: 57.85, mapY: 67.63, accent: '#81892A' },
  { id: 'lr', isoCode: 'LR', nameJa: 'リベリア', nameEn: 'Liberia', flag: '🇱🇷', region: 'アフリカ', continent: 'アフリカ', mapX: 47.43, mapY: 46.05, accent: '#82892A' },
  { id: 'ly', isoCode: 'LY', nameJa: 'リビア', nameEn: 'Libya', flag: '🇱🇾', region: 'アフリカ', continent: 'アフリカ', mapX: 54.69, mapY: 33.55, accent: '#77892A' },
  { id: 'mg', isoCode: 'MG', nameJa: 'マダガスカル', nameEn: 'Madagascar', flag: '🇲🇬', region: 'アフリカ', continent: 'アフリカ', mapX: 63.04, mapY: 60.9, accent: '#63892A' },
  { id: 'mw', isoCode: 'MW', nameJa: 'マラウイ', nameEn: 'Malawi', flag: '🇲🇼', region: 'アフリカ', continent: 'アフリカ', mapX: 59.48, mapY: 57.71, accent: '#898829' },
  { id: 'ml', isoCode: 'ML', nameJa: 'マリ', nameEn: 'Mali', flag: '🇲🇱', region: 'アフリカ', continent: 'アフリカ', mapX: 48.59, mapY: 40.8, accent: '#89762A' },
  { id: 'mr', isoCode: 'MR', nameJa: 'モーリタニア', nameEn: 'Mauritania', flag: '🇲🇷', region: 'アフリカ', continent: 'アフリカ', mapX: 46.71, mapY: 38.28, accent: '#898029' },
  { id: 'mu', isoCode: 'MU', nameJa: 'モーリシャス', nameEn: 'Mauritius', flag: '🇲🇺', region: 'アフリカ', continent: 'アフリカ', mapX: 61, mapY: 71, accent: '#898529' },
  { id: 'mz', isoCode: 'MZ', nameJa: 'モザンビーク', nameEn: 'Mozambique', flag: '🇲🇿', region: 'アフリカ', continent: 'アフリカ', mapX: 59.78, mapY: 60.74, accent: '#868929' },
  { id: 'na', isoCode: 'NA', nameJa: 'ナミビア', nameEn: 'Namibia', flag: '🇳🇦', region: 'アフリカ', continent: 'アフリカ', mapX: 55.03, mapY: 63.18, accent: '#7D8929' },
  { id: 'ne', isoCode: 'NE', nameJa: 'ニジェール', nameEn: 'Niger', flag: '🇳🇪', region: 'アフリカ', continent: 'アフリカ', mapX: 52.36, mapY: 40.29, accent: '#768929' },
  { id: 'ng', isoCode: 'NG', nameJa: 'ナイジェリア', nameEn: 'Nigeria', flag: '🇳🇬', region: 'アフリカ', continent: 'アフリカ', mapX: 52.35, mapY: 44.37, accent: '#738929' },
  { id: 'rw', isoCode: 'RW', nameJa: 'ルワンダ', nameEn: 'Rwanda', flag: '🇷🇼', region: 'アフリカ', continent: 'アフリカ', mapX: 58.31, mapY: 51.19, accent: '#8E7C25' },
  { id: 'st', isoCode: 'ST', nameJa: 'サントメ・プリンシペ', nameEn: 'Sao Tome and Principe', flag: '🇸🇹', region: 'アフリカ', continent: 'アフリカ', mapX: 48, mapY: 60, accent: '#6F8F24' },
  { id: 'sn', isoCode: 'SN', nameJa: 'セネガル', nameEn: 'Senegal', flag: '🇸🇳', region: 'アフリカ', continent: 'アフリカ', mapX: 45.95, mapY: 41.6, accent: '#798E25' },
  { id: 'sc', isoCode: 'SC', nameJa: 'セーシェル', nameEn: 'Seychelles', flag: '🇸🇨', region: 'アフリカ', continent: 'アフリカ', mapX: 60, mapY: 64, accent: '#8C8E25' },
  { id: 'sl', isoCode: 'SL', nameJa: 'シエラレオネ', nameEn: 'Sierra Leone', flag: '🇸🇱', region: 'アフリカ', continent: 'アフリカ', mapX: 46.75, mapY: 44.93, accent: '#7C8E25' },
  { id: 'so', isoCode: 'SO', nameJa: 'ソマリア', nameEn: 'Somalia', flag: '🇸🇴', region: 'アフリカ', continent: 'アフリカ', mapX: 62.93, mapY: 46.43, accent: '#778E25' },
  { id: 'ss', isoCode: 'SS', nameJa: '南スーダン', nameEn: 'South Sudan', flag: '🇸🇸', region: 'アフリカ', continent: 'アフリカ', mapX: 58.31, mapY: 45.27, accent: '#708F24' },
  { id: 'sd', isoCode: 'SD', nameJa: 'スーダン', nameEn: 'Sudan', flag: '🇸🇩', region: 'アフリカ', continent: 'アフリカ', mapX: 58.24, mapY: 41.83, accent: '#8A8E25' },
  { id: 'tz', isoCode: 'TZ', nameJa: 'タンザニア', nameEn: 'Tanzania', flag: '🇹🇿', region: 'アフリカ', continent: 'アフリカ', mapX: 59.59, mapY: 53.84, accent: '#6C7D36' },
  { id: 'tg', isoCode: 'TG', nameJa: 'トーゴ', nameEn: 'Togo', flag: '🇹🇬', region: 'アフリカ', continent: 'アフリカ', mapX: 50.25, mapY: 44.81, accent: '#8F8624' },
  { id: 'tn', isoCode: 'TN', nameJa: 'チュニジア', nameEn: 'Tunisia', flag: '🇹🇳', region: 'アフリカ', continent: 'アフリカ', mapX: 52.69, mapY: 29.8, accent: '#8B8F24' },
  { id: 'ug', isoCode: 'UG', nameJa: 'ウガンダ', nameEn: 'Uganda', flag: '🇺🇬', region: 'アフリカ', continent: 'アフリカ', mapX: 58.92, mapY: 49.19, accent: '#7D6B36' },
  { id: 'zm', isoCode: 'ZM', nameJa: 'ザンビア', nameEn: 'Zambia', flag: '🇿🇲', region: 'アフリカ', continent: 'アフリカ', mapX: 57.74, mapY: 57.71, accent: '#638131' },
  { id: 'zw', isoCode: 'ZW', nameJa: 'ジンバブエ', nameEn: 'Zimbabwe', flag: '🇿🇼', region: 'アフリカ', continent: 'アフリカ', mapX: 58.17, mapY: 61.23, accent: '#817731' },
  { id: 'ki', isoCode: 'KI', nameJa: 'キリバス', nameEn: 'Kiribati', flag: '🇰🇮', region: 'オセアニア', continent: 'オセアニア', mapX: 96, mapY: 62, accent: '#4399A3' },
  { id: 'mh', isoCode: 'MH', nameJa: 'マーシャル諸島', nameEn: 'Marshall Islands', flag: '🇲🇭', region: 'オセアニア', continent: 'オセアニア', mapX: 92, mapY: 58, accent: '#4079A5' },
  { id: 'fm', isoCode: 'FM', nameJa: 'ミクロネシア連邦', nameEn: 'Micronesia', flag: '🇫🇲', region: 'オセアニア', continent: 'オセアニア', mapX: 88, mapY: 60, accent: '#47839E' },
  { id: 'nr', isoCode: 'NR', nameJa: 'ナウル', nameEn: 'Nauru', flag: '🇳🇷', region: 'オセアニア', continent: 'オセアニア', mapX: 91, mapY: 63, accent: '#3E7AA8' },
  { id: 'pw', isoCode: 'PW', nameJa: 'パラオ', nameEn: 'Palau', flag: '🇵🇼', region: 'オセアニア', continent: 'オセアニア', mapX: 85, mapY: 59, accent: '#3C96AA' },
  { id: 'pg', isoCode: 'PG', nameJa: 'パプアニューギニア', nameEn: 'Papua New Guinea', flag: '🇵🇬', region: 'オセアニア', continent: 'オセアニア', mapX: 91.44, mapY: 53.76, accent: '#3DA9A0' },
  { id: 'ws', isoCode: 'WS', nameJa: 'サモア', nameEn: 'Samoa', flag: '🇼🇸', region: 'オセアニア', continent: 'オセアニア', mapX: 95, mapY: 70, accent: '#4D8199' },
  { id: 'sb', isoCode: 'SB', nameJa: 'ソロモン諸島', nameEn: 'Solomon Islands', flag: '🇸🇧', region: 'オセアニア', continent: 'オセアニア', mapX: 94.35, mapY: 55.22, accent: '#39AAAC' },
  { id: 'to', isoCode: 'TO', nameJa: 'トンガ', nameEn: 'Tonga', flag: '🇹🇴', region: 'オセアニア', continent: 'オセアニア', mapX: 94, mapY: 73, accent: '#38A5AD' },
  { id: 'tv', isoCode: 'TV', nameJa: 'ツバル', nameEn: 'Tuvalu', flag: '🇹🇻', region: 'オセアニア', continent: 'オセアニア', mapX: 93, mapY: 67, accent: '#4F8996' },
  { id: 'vu', isoCode: 'VU', nameJa: 'バヌアツ', nameEn: 'Vanuatu', flag: '🇻🇺', region: 'オセアニア', continent: 'オセアニア', mapX: 91, mapY: 71, accent: '#4E978B' },
  { id: 'ck', isoCode: 'CK', nameJa: 'クック諸島', nameEn: 'Cook Islands', flag: '🇨🇰', region: 'オセアニア', continent: 'オセアニア', mapX: 98, mapY: 75, accent: '#4B939B' },
];

export const COUNTRY_BY_ID = Object.fromEntries(COUNTRIES.map((country) => [country.id, country])) as Record<string, Country>;

export const REGION_ORDER = ['アジア', 'ヨーロッパ', '北米', '南米', 'アフリカ', 'オセアニア'] as const;

export function searchCountries(query: string) {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return COUNTRIES;
  }

  return COUNTRIES.filter((country) =>
    [country.nameJa, country.nameEn, country.isoCode].some((value) => value.toLowerCase().includes(normalized)),
  );
}

